//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab29_custom_web_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public string Rating { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
        public string Director { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
